blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/uxmansarwar/response/discussions
    about: Ask questions or suggest new ideas.
  - name: 📖 Documentation
    url: https://github.com/uxmansarwar/response/wiki
    about: Check the official documentation before submitting an issue.
